/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as StudentsImport } from './routes/students'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as StudentsStudentIDImport } from './routes/students_.$studentID'

// Create/Update Routes

const StudentsRoute = StudentsImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const StudentsStudentIDRoute = StudentsStudentIDImport.update({
  id: '/students_/$studentID',
  path: '/students/$studentID',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/students': {
      id: '/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof StudentsImport
      parentRoute: typeof rootRoute
    }
    '/students_/$studentID': {
      id: '/students_/$studentID'
      path: '/students/$studentID'
      fullPath: '/students/$studentID'
      preLoaderRoute: typeof StudentsStudentIDImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/students': typeof StudentsRoute
  '/students/$studentID': typeof StudentsStudentIDRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/students': typeof StudentsRoute
  '/students/$studentID': typeof StudentsStudentIDRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/students': typeof StudentsRoute
  '/students_/$studentID': typeof StudentsStudentIDRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/students' | '/students/$studentID'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/students' | '/students/$studentID'
  id: '__root__' | '/' | '/about' | '/students' | '/students_/$studentID'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  StudentsRoute: typeof StudentsRoute
  StudentsStudentIDRoute: typeof StudentsStudentIDRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  StudentsRoute: StudentsRoute,
  StudentsStudentIDRoute: StudentsStudentIDRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/students",
        "/students_/$studentID"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/students": {
      "filePath": "students.tsx"
    },
    "/students_/$studentID": {
      "filePath": "students_.$studentID.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
